ol.proj.proj4.register(proj4);
//ol.proj.get("EPSG:3116").setExtent([948583.870888, 978383.415364, 1046567.903519, 1033361.815696]);
var wms_layers = [];


        var lyr_OpenStreetMap_0 = new ol.layer.Tile({
            'title': 'OpenStreetMap',
            //'type': 'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
    attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_SubndicedeConvivenciayCulturadePazporBarrio_1 = new ol.format.GeoJSON();
var features_SubndicedeConvivenciayCulturadePazporBarrio_1 = format_SubndicedeConvivenciayCulturadePazporBarrio_1.readFeatures(json_SubndicedeConvivenciayCulturadePazporBarrio_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3116'});
var jsonSource_SubndicedeConvivenciayCulturadePazporBarrio_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_SubndicedeConvivenciayCulturadePazporBarrio_1.addFeatures(features_SubndicedeConvivenciayCulturadePazporBarrio_1);
var lyr_SubndicedeConvivenciayCulturadePazporBarrio_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_SubndicedeConvivenciayCulturadePazporBarrio_1, 
                style: style_SubndicedeConvivenciayCulturadePazporBarrio_1,
                popuplayertitle: "Subíndice de Convivencia y Cultura de Paz por Barrio",
                interactive: true,
    title: 'Subíndice de Convivencia y Cultura de Paz por Barrio<br />\
    <img src="styles/legend/SubndicedeConvivenciayCulturadePazporBarrio_1_0.png" /> -0.105 - 0.015<br />\
    <img src="styles/legend/SubndicedeConvivenciayCulturadePazporBarrio_1_1.png" /> 0.015 - 0.041<br />\
    <img src="styles/legend/SubndicedeConvivenciayCulturadePazporBarrio_1_2.png" /> 0.041 - 0.059<br />\
    <img src="styles/legend/SubndicedeConvivenciayCulturadePazporBarrio_1_3.png" /> 0.059 - 0.082<br />\
    <img src="styles/legend/SubndicedeConvivenciayCulturadePazporBarrio_1_4.png" /> 0.082 - 0.267<br />'
        });
var format_SubndicedeCulturaAmbientalporBarrio_2 = new ol.format.GeoJSON();
var features_SubndicedeCulturaAmbientalporBarrio_2 = format_SubndicedeCulturaAmbientalporBarrio_2.readFeatures(json_SubndicedeCulturaAmbientalporBarrio_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3116'});
var jsonSource_SubndicedeCulturaAmbientalporBarrio_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_SubndicedeCulturaAmbientalporBarrio_2.addFeatures(features_SubndicedeCulturaAmbientalporBarrio_2);
var lyr_SubndicedeCulturaAmbientalporBarrio_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_SubndicedeCulturaAmbientalporBarrio_2, 
                style: style_SubndicedeCulturaAmbientalporBarrio_2,
                popuplayertitle: "Subíndice de Cultura Ambiental por Barrio",
                interactive: true,
    title: 'Subíndice de Cultura Ambiental por Barrio<br />\
    <img src="styles/legend/SubndicedeCulturaAmbientalporBarrio_2_0.png" /> 0.148 - 0.205<br />\
    <img src="styles/legend/SubndicedeCulturaAmbientalporBarrio_2_1.png" /> 0.205 - 0.218<br />\
    <img src="styles/legend/SubndicedeCulturaAmbientalporBarrio_2_2.png" /> 0.218 - 0.229<br />\
    <img src="styles/legend/SubndicedeCulturaAmbientalporBarrio_2_3.png" /> 0.229 - 0.244<br />\
    <img src="styles/legend/SubndicedeCulturaAmbientalporBarrio_2_4.png" /> 0.244 - 0.319<br />'
        });
var format_SubndicedeCulturaPolticayCiudadanaporBarrio_3 = new ol.format.GeoJSON();
var features_SubndicedeCulturaPolticayCiudadanaporBarrio_3 = format_SubndicedeCulturaPolticayCiudadanaporBarrio_3.readFeatures(json_SubndicedeCulturaPolticayCiudadanaporBarrio_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3116'});
var jsonSource_SubndicedeCulturaPolticayCiudadanaporBarrio_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_SubndicedeCulturaPolticayCiudadanaporBarrio_3.addFeatures(features_SubndicedeCulturaPolticayCiudadanaporBarrio_3);
var lyr_SubndicedeCulturaPolticayCiudadanaporBarrio_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_SubndicedeCulturaPolticayCiudadanaporBarrio_3, 
                style: style_SubndicedeCulturaPolticayCiudadanaporBarrio_3,
                popuplayertitle: "Subíndice de Cultura Política y Ciudadanía por Barrio",
                interactive: true,
    title: 'Subíndice de Cultura Política y Ciudadanía por Barrio<br />\
    <img src="styles/legend/SubndicedeCulturaPolticayCiudadanaporBarrio_3_0.png" /> -0.0032 - 0.1738<br />\
    <img src="styles/legend/SubndicedeCulturaPolticayCiudadanaporBarrio_3_1.png" /> 0.1738 - 0.1822<br />\
    <img src="styles/legend/SubndicedeCulturaPolticayCiudadanaporBarrio_3_2.png" /> 0.1822 - 0.187<br />\
    <img src="styles/legend/SubndicedeCulturaPolticayCiudadanaporBarrio_3_3.png" /> 0.187 - 0.1928<br />\
    <img src="styles/legend/SubndicedeCulturaPolticayCiudadanaporBarrio_3_4.png" /> 0.1928 - 0.3415<br />'
        });
var format_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4 = new ol.format.GeoJSON();
var features_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4 = format_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4.readFeatures(json_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3116'});
var jsonSource_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4.addFeatures(features_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4);
var lyr_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4, 
                style: style_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4,
                popuplayertitle: "Subíndice de Equidad de Género y Eliminación del Machismo por Barrio",
                interactive: true,
    title: 'Subíndice de Equidad de Género y Eliminación del Machismo por Barrio<br />\
    <img src="styles/legend/SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4_0.png" /> 0.097 - 0.319<br />\
    <img src="styles/legend/SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4_1.png" /> 0.319 - 0.333<br />\
    <img src="styles/legend/SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4_2.png" /> 0.333 - 0.344<br />\
    <img src="styles/legend/SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4_3.png" /> 0.344 - 0.361<br />\
    <img src="styles/legend/SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4_4.png" /> 0.361 - 0.477<br />'
        });
var format_SubndicedeEspacioPblicoporBarrio_5 = new ol.format.GeoJSON();
var features_SubndicedeEspacioPblicoporBarrio_5 = format_SubndicedeEspacioPblicoporBarrio_5.readFeatures(json_SubndicedeEspacioPblicoporBarrio_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3116'});
var jsonSource_SubndicedeEspacioPblicoporBarrio_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_SubndicedeEspacioPblicoporBarrio_5.addFeatures(features_SubndicedeEspacioPblicoporBarrio_5);
var lyr_SubndicedeEspacioPblicoporBarrio_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_SubndicedeEspacioPblicoporBarrio_5, 
                style: style_SubndicedeEspacioPblicoporBarrio_5,
                popuplayertitle: "Subíndice de Espacio Público por Barrio",
                interactive: true,
    title: 'Subíndice de Espacio Público por Barrio<br />\
    <img src="styles/legend/SubndicedeEspacioPblicoporBarrio_5_0.png" /> 0.328 - 0.46<br />\
    <img src="styles/legend/SubndicedeEspacioPblicoporBarrio_5_1.png" /> 0.46 - 0.481<br />\
    <img src="styles/legend/SubndicedeEspacioPblicoporBarrio_5_2.png" /> 0.481 - 0.497<br />\
    <img src="styles/legend/SubndicedeEspacioPblicoporBarrio_5_3.png" /> 0.497 - 0.519<br />\
    <img src="styles/legend/SubndicedeEspacioPblicoporBarrio_5_4.png" /> 0.519 - 0.587<br />'
        });
var format_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6 = new ol.format.GeoJSON();
var features_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6 = format_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6.readFeatures(json_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3116'});
var jsonSource_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6.addFeatures(features_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6);
var lyr_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6, 
                style: style_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6,
                popuplayertitle: "Subíndice de Inclusión e Identidades Sociales Diversas por Barrio",
                interactive: true,
    title: 'Subíndice de Inclusión e Identidades Sociales Diversas por Barrio<br />\
    <img src="styles/legend/SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6_0.png" /> 0.3685 - 0.5533<br />\
    <img src="styles/legend/SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6_1.png" /> 0.5533 - 0.5607<br />\
    <img src="styles/legend/SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6_2.png" /> 0.5607 - 0.5672<br />\
    <img src="styles/legend/SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6_3.png" /> 0.5672 - 0.5751<br />\
    <img src="styles/legend/SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6_4.png" /> 0.5751 - 0.7042<br />'
        });
var format_SubndicedeMovilidadporBarrio_7 = new ol.format.GeoJSON();
var features_SubndicedeMovilidadporBarrio_7 = format_SubndicedeMovilidadporBarrio_7.readFeatures(json_SubndicedeMovilidadporBarrio_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3116'});
var jsonSource_SubndicedeMovilidadporBarrio_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_SubndicedeMovilidadporBarrio_7.addFeatures(features_SubndicedeMovilidadporBarrio_7);
var lyr_SubndicedeMovilidadporBarrio_7 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_SubndicedeMovilidadporBarrio_7, 
                style: style_SubndicedeMovilidadporBarrio_7,
                popuplayertitle: "Subíndice de Movilidad por Barrio",
                interactive: true,
    title: 'Subíndice de Movilidad por Barrio<br />\
    <img src="styles/legend/SubndicedeMovilidadporBarrio_7_0.png" /> 0.162 - 0.377<br />\
    <img src="styles/legend/SubndicedeMovilidadporBarrio_7_1.png" /> 0.377 - 0.394<br />\
    <img src="styles/legend/SubndicedeMovilidadporBarrio_7_2.png" /> 0.394 - 0.411<br />\
    <img src="styles/legend/SubndicedeMovilidadporBarrio_7_3.png" /> 0.411 - 0.434<br />\
    <img src="styles/legend/SubndicedeMovilidadporBarrio_7_4.png" /> 0.434 - 0.548<br />'
        });

lyr_OpenStreetMap_0.setVisible(true);lyr_SubndicedeConvivenciayCulturadePazporBarrio_1.setVisible(false);lyr_SubndicedeCulturaAmbientalporBarrio_2.setVisible(false);lyr_SubndicedeCulturaPolticayCiudadanaporBarrio_3.setVisible(false);lyr_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4.setVisible(false);lyr_SubndicedeEspacioPblicoporBarrio_5.setVisible(false);lyr_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6.setVisible(false);lyr_SubndicedeMovilidadporBarrio_7.setVisible(true);
var layersList = [lyr_OpenStreetMap_0,lyr_SubndicedeConvivenciayCulturadePazporBarrio_1,lyr_SubndicedeCulturaAmbientalporBarrio_2,lyr_SubndicedeCulturaPolticayCiudadanaporBarrio_3,lyr_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4,lyr_SubndicedeEspacioPblicoporBarrio_5,lyr_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6,lyr_SubndicedeMovilidadporBarrio_7];
lyr_SubndicedeConvivenciayCulturadePazporBarrio_1.set('fieldAliases', {'FID': 'FID', 'SCACODIGO': 'SCACODIGO', 'SCATIPO': 'SCATIPO', 'SCANOMBRE': 'SCANOMBRE', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Densidad_Eventos': 'Densidad_Eventos', 'Densidad_Intervenciones': 'Densidad_Intervenciones', 'ICC_2021': 'ICC_2021', 'ICC_2023': 'ICC_2023', 'Equip': 'Equip', 'I_194_Mul': 'I_194_Mul', 'I_127_Poi': 'I_127_Poi', 'Densidad_Eventos_2021': 'Densidad_Eventos_2021', 'Densidad_Intervenciones_2021': 'Densidad_Intervenciones_2021', 'Densidad_Eventos_2023': 'Densidad_Eventos_2023', 'Densidad_Intervenciones_2023': 'Densidad_Intervenciones_2023', 'Densidad_Eventos_2021_inv': 'Densidad_Eventos_2021_inv', 'Densidad_Eventos_2023_inv': 'Densidad_Eventos_2023_inv', 'Densidad_Intervenciones_2021_inv': 'Densidad_Intervenciones_2021_inv', 'Densidad_Intervenciones_2023_inv': 'Densidad_Intervenciones_2023_inv', 'Densidad_Intervenciones_inv': 'Densidad_Intervenciones_inv', 'Densidad_Eventos_inv': 'Densidad_Eventos_inv', 'Equip_inv': 'Equip_inv', 'I_127_Poi_inv': 'I_127_Poi_inv', 'delta_ICC': 'delta_ICC', 'delta_eventos': 'delta_eventos', 'delta_intervenciones': 'delta_intervenciones', 'indice_intervencion': 'indice_intervencion', 'OBJECTID': 'OBJECTID', 'SUECODIGO': 'SUECODIGO', 'SUECSUELO': 'SUECSUELO', 'SUEAADMIN': 'SUEAADMIN', 'SUEAREA': 'SUEAREA', 'SHAPE.AREA': 'SHAPE.AREA', 'SHAPE.LEN': 'SHAPE.LEN', });
lyr_SubndicedeCulturaAmbientalporBarrio_2.set('fieldAliases', {'FID': 'FID', 'SCACODIGO': 'SCACODIGO', 'SCATIPO': 'SCATIPO', 'SCANOMBRE': 'SCANOMBRE', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Densidad_Eventos': 'Densidad_Eventos', 'Densidad_Intervenciones': 'Densidad_Intervenciones', 'ICC_2021': 'ICC_2021', 'ICC_2023': 'ICC_2023', 'Equip_x': 'Equip_x', 'IActores': 'IActores', 'IReserva': 'IReserva', 'I_5_Poi': 'I_5_Poi', 'I_9_Poi': 'I_9_Poi', 'I_23_Poi': 'I_23_Poi', 'I_167_Pol': 'I_167_Pol', 'I_20_Mul': 'I_20_Mul', 'I_25_Poi': 'I_25_Poi', 'I_22_Mul': 'I_22_Mul', 'I_14_Mul': 'I_14_Mul', 'I_15_Mul': 'I_15_Mul', 'I_16_Poi': 'I_16_Poi', 'I_17_Mul': 'I_17_Mul', 'I_34_Poi': 'I_34_Poi', 'I_33_Mul': 'I_33_Mul', 'I_166_Poi': 'I_166_Poi', 'I_24_Poi': 'I_24_Poi', 'Densidad_Eventos_2021': 'Densidad_Eventos_2021', 'Densidad_Intervenciones_2021': 'Densidad_Intervenciones_2021', 'Densidad_Eventos_2023': 'Densidad_Eventos_2023', 'Densidad_Intervenciones_2023': 'Densidad_Intervenciones_2023', 'Densidad_Eventos_2021_inv': 'Densidad_Eventos_2021_inv', 'Densidad_Eventos_2023_inv': 'Densidad_Eventos_2023_inv', 'Equip_x_inv': 'Equip_x_inv', 'I_9_Poi_inv': 'I_9_Poi_inv', 'I_23_Poi_inv': 'I_23_Poi_inv', 'I_16_Poi_inv': 'I_16_Poi_inv', 'I_25_Poi_inv': 'I_25_Poi_inv', 'I_166_Poi_inv': 'I_166_Poi_inv', 'delta_ICC': 'delta_ICC', 'delta_eventos': 'delta_eventos', 'delta_intervenciones': 'delta_intervenciones', 'indice_intervencion': 'indice_intervencion', 'OBJECTID': 'OBJECTID', 'SUECODIGO': 'SUECODIGO', 'SUECSUELO': 'SUECSUELO', 'SUEAADMIN': 'SUEAADMIN', 'SUEAREA': 'SUEAREA', 'SHAPE.AREA': 'SHAPE.AREA', 'SHAPE.LEN': 'SHAPE.LEN', });
lyr_SubndicedeCulturaPolticayCiudadanaporBarrio_3.set('fieldAliases', {'FID': 'FID', 'SCACODIGO': 'SCACODIGO', 'SCATIPO': 'SCATIPO', 'SCANOMBRE': 'SCANOMBRE', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Densidad_Eventos': 'Densidad_Eventos', 'Densidad_Intervenciones': 'Densidad_Intervenciones', 'ICC_2021': 'ICC_2021', 'ICC_2023': 'ICC_2023', 'IPolEquip': 'IPolEquip', 'IPolActores': 'IPolActores', 'I_39_Mul': 'I_39_Mul', 'I_40_Mul': 'I_40_Mul', 'I_158_Pol': 'I_158_Pol', 'I_74_Poi': 'I_74_Poi', 'Densidad_Eventos_2021': 'Densidad_Eventos_2021', 'Densidad_Intervenciones_2021': 'Densidad_Intervenciones_2021', 'Densidad_Eventos_2023': 'Densidad_Eventos_2023', 'Densidad_Intervenciones_2023': 'Densidad_Intervenciones_2023', 'Densidad_Eventos_2021_inv': 'Densidad_Eventos_2021_inv', 'Densidad_Eventos_2023_inv': 'Densidad_Eventos_2023_inv', 'Densidad_Intervenciones_2021_inv': 'Densidad_Intervenciones_2021_inv', 'Densidad_Intervenciones_2023_inv': 'Densidad_Intervenciones_2023_inv', 'Densidad_Intervenciones_inv': 'Densidad_Intervenciones_inv', 'Densidad_Eventos_inv': 'Densidad_Eventos_inv', 'IPolEquip_inv': 'IPolEquip_inv', 'IPolActores_inv': 'IPolActores_inv', 'I_158_Pol_inv': 'I_158_Pol_inv', 'delta_ICC': 'delta_ICC', 'delta_eventos': 'delta_eventos', 'delta_intervenciones': 'delta_intervenciones', 'indice_intervencion': 'indice_intervencion', 'OBJECTID': 'OBJECTID', 'SUECODIGO': 'SUECODIGO', 'SUECSUELO': 'SUECSUELO', 'SUEAADMIN': 'SUEAADMIN', 'SUEAREA': 'SUEAREA', 'SHAPE.AREA': 'SHAPE.AREA', 'SHAPE.LEN': 'SHAPE.LEN', });
lyr_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4.set('fieldAliases', {'FID': 'FID', 'SCACODIGO': 'SCACODIGO', 'SCATIPO': 'SCATIPO', 'SCANOMBRE': 'SCANOMBRE', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Densidad_Eventos': 'Densidad_Eventos', 'Densidad_Intervenciones': 'Densidad_Intervenciones', 'ICC_2021': 'ICC_2021', 'ICC_2023': 'ICC_2023', 'Equip': 'Equip', 'I_181_Mul': 'I_181_Mul', 'I_140_Pol': 'I_140_Pol', 'Densidad_Eventos_2021': 'Densidad_Eventos_2021', 'Densidad_Intervenciones_2021': 'Densidad_Intervenciones_2021', 'Densidad_Eventos_2023': 'Densidad_Eventos_2023', 'Densidad_Intervenciones_2023': 'Densidad_Intervenciones_2023', 'Equip_inv': 'Equip_inv', 'I_181_Mul_inv': 'I_181_Mul_inv', 'Densidad_Eventos_2021_inv': 'Densidad_Eventos_2021_inv', 'Densidad_Eventos_2023_inv': 'Densidad_Eventos_2023_inv', 'Densidad_Intervenciones_2021_inv': 'Densidad_Intervenciones_2021_inv', 'Densidad_Intervenciones_2023_inv': 'Densidad_Intervenciones_2023_inv', 'delta_ICC': 'delta_ICC', 'delta_eventos': 'delta_eventos', 'delta_intervenciones': 'delta_intervenciones', 'indice_intervencion': 'indice_intervencion', 'OBJECTID': 'OBJECTID', 'SUECODIGO': 'SUECODIGO', 'SUECSUELO': 'SUECSUELO', 'SUEAADMIN': 'SUEAADMIN', 'SUEAREA': 'SUEAREA', 'SHAPE.AREA': 'SHAPE.AREA', 'SHAPE.LEN': 'SHAPE.LEN', });
lyr_SubndicedeEspacioPblicoporBarrio_5.set('fieldAliases', {'FID': 'FID', 'SCACODIGO': 'SCACODIGO', 'SCATIPO': 'SCATIPO', 'SCANOMBRE': 'SCANOMBRE', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Densidad_Eventos': 'Densidad_Eventos', 'Densidad_Intervenciones': 'Densidad_Intervenciones', 'ICC_2021': 'ICC_2021', 'ICC_2023': 'ICC_2023', 'Equip': 'Equip', 'I_71_Mul': 'I_71_Mul', 'I_55_Pol': 'I_55_Pol', 'I_39_Mul': 'I_39_Mul', 'I_145_Pol': 'I_145_Pol', 'I_40_Mul': 'I_40_Mul', 'I_140_Pol': 'I_140_Pol', 'I_196_Pol': 'I_196_Pol', 'I_3_Mul': 'I_3_Mul', 'I_149_Pol': 'I_149_Pol', 'Densidad_Eventos_2021': 'Densidad_Eventos_2021', 'Densidad_Intervenciones_2021': 'Densidad_Intervenciones_2021', 'Densidad_Eventos_2023': 'Densidad_Eventos_2023', 'Densidad_Intervenciones_2023': 'Densidad_Intervenciones_2023', 'Equip_inv': 'Equip_inv', 'I_71_Mul_inv': 'I_71_Mul_inv', 'I_55_Pol_inv': 'I_55_Pol_inv', 'I_145_Pol_inv': 'I_145_Pol_inv', 'I_140_Pol_inv': 'I_140_Pol_inv', 'I_196_Pol_inv': 'I_196_Pol_inv', 'I_3_Mul_inv': 'I_3_Mul_inv', 'Densidad_Eventos_inv': 'Densidad_Eventos_inv', 'delta_ICC': 'delta_ICC', 'delta_eventos': 'delta_eventos', 'delta_intervenciones': 'delta_intervenciones', 'indice_intervencion': 'indice_intervencion', 'OBJECTID': 'OBJECTID', 'SUECODIGO': 'SUECODIGO', 'SUECSUELO': 'SUECSUELO', 'SUEAADMIN': 'SUEAADMIN', 'SUEAREA': 'SUEAREA', 'SHAPE.AREA': 'SHAPE.AREA', 'SHAPE.LEN': 'SHAPE.LEN', });
lyr_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6.set('fieldAliases', {'FID': 'FID', 'SCACODIGO': 'SCACODIGO', 'SCATIPO': 'SCATIPO', 'SCANOMBRE': 'SCANOMBRE', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Densidad_Eventos': 'Densidad_Eventos', 'Densidad_Intervenciones': 'Densidad_Intervenciones', 'ICC_2021': 'ICC_2021', 'ICC_2023': 'ICC_2023', 'Equip': 'Equip', 'I_125_Poi': 'I_125_Poi', 'I_101_Poi': 'I_101_Poi', 'I_78_Poi': 'I_78_Poi', 'I_126_Poi': 'I_126_Poi', 'I_129_Poi': 'I_129_Poi', 'I_111_Poi': 'I_111_Poi', 'I_199_Pol': 'I_199_Pol', 'I_106_Poi': 'I_106_Poi', 'I_142_Pol': 'I_142_Pol', 'I_102_Poi': 'I_102_Poi', 'I_122_Poi': 'I_122_Poi', 'I_123_Poi': 'I_123_Poi', 'I_108_Poi': 'I_108_Poi', 'I_104_Poi': 'I_104_Poi', 'I_132_Poi': 'I_132_Poi', 'I_98_Poi': 'I_98_Poi', 'I_120_Poi': 'I_120_Poi', 'I_99_Poi': 'I_99_Poi', 'Densidad_Eventos_2021': 'Densidad_Eventos_2021', 'Densidad_Intervenciones_2021': 'Densidad_Intervenciones_2021', 'Densidad_Eventos_2023': 'Densidad_Eventos_2023', 'Densidad_Intervenciones_2023': 'Densidad_Intervenciones_2023', 'Equip_inv': 'Equip_inv', 'I_125_Poi_inv': 'I_125_Poi_inv', 'I_101_Poi_inv': 'I_101_Poi_inv', 'I_78_Poi_inv': 'I_78_Poi_inv', 'I_126_Poi_inv': 'I_126_Poi_inv', 'I_129_Poi_inv': 'I_129_Poi_inv', 'I_111_Poi_inv': 'I_111_Poi_inv', 'I_106_Poi_inv': 'I_106_Poi_inv', 'I_102_Poi_inv': 'I_102_Poi_inv', 'I_122_Poi_inv': 'I_122_Poi_inv', 'I_123_Poi_inv': 'I_123_Poi_inv', 'I_108_Poi_inv': 'I_108_Poi_inv', 'I_104_Poi_inv': 'I_104_Poi_inv', 'I_132_Poi_inv': 'I_132_Poi_inv', 'I_98_Poi_inv': 'I_98_Poi_inv', 'I_120_Poi_inv': 'I_120_Poi_inv', 'I_99_Poi_inv': 'I_99_Poi_inv', 'Densidad_Eventos_2021_inv': 'Densidad_Eventos_2021_inv', 'Densidad_Eventos_2023_inv': 'Densidad_Eventos_2023_inv', 'Densidad_Intervenciones_2021_inv': 'Densidad_Intervenciones_2021_inv', 'Densidad_Intervenciones_2023_inv': 'Densidad_Intervenciones_2023_inv', 'delta_ICC': 'delta_ICC', 'delta_eventos': 'delta_eventos', 'delta_intervenciones': 'delta_intervenciones', 'indice_intervencion': 'indice_intervencion', 'OBJECTID': 'OBJECTID', 'SUECODIGO': 'SUECODIGO', 'SUECSUELO': 'SUECSUELO', 'SUEAADMIN': 'SUEAADMIN', 'SUEAREA': 'SUEAREA', 'SHAPE.AREA': 'SHAPE.AREA', 'SHAPE.LEN': 'SHAPE.LEN', });
lyr_SubndicedeMovilidadporBarrio_7.set('fieldAliases', {'FID': 'FID', 'SCACODIGO': 'SCACODIGO', 'SCATIPO': 'SCATIPO', 'SCANOMBRE': 'SCANOMBRE', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Densidad_Eventos': 'Densidad_Eventos', 'Densidad_Intervenciones': 'Densidad_Intervenciones', 'ICC_2021': 'ICC_2021', 'ICC_2023': 'ICC_2023', 'Equip': 'Equip', 'I_71_Mul': 'I_71_Mul', 'I_42_Mul': 'I_42_Mul', 'I_153_Poi': 'I_153_Poi', 'I_139_Lin': 'I_139_Lin', 'I_159_Lin': 'I_159_Lin', 'Densidad_Eventos_2021': 'Densidad_Eventos_2021', 'Densidad_Intervenciones_2021': 'Densidad_Intervenciones_2021', 'Densidad_Eventos_2023': 'Densidad_Eventos_2023', 'Densidad_Intervenciones_2023': 'Densidad_Intervenciones_2023', 'Equip_inv': 'Equip_inv', 'I_71_Mul_inv': 'I_71_Mul_inv', 'I_153_Poi_inv': 'I_153_Poi_inv', 'I_139_Lin_inv': 'I_139_Lin_inv', 'I_159_Lin_inv': 'I_159_Lin_inv', 'Densidad_Eventos_2021_inv': 'Densidad_Eventos_2021_inv', 'Densidad_Eventos_2023_inv': 'Densidad_Eventos_2023_inv', 'Densidad_Intervenciones_2021_inv': 'Densidad_Intervenciones_2021_inv', 'Densidad_Intervenciones_2023_inv': 'Densidad_Intervenciones_2023_inv', 'delta_ICC': 'delta_ICC', 'delta_eventos': 'delta_eventos', 'delta_intervenciones': 'delta_intervenciones', 'indice_intervencion': 'indice_intervencion', 'OBJECTID': 'OBJECTID', 'SUECODIGO': 'SUECODIGO', 'SUECSUELO': 'SUECSUELO', 'SUEAADMIN': 'SUEAADMIN', 'SUEAREA': 'SUEAREA', 'SHAPE.AREA': 'SHAPE.AREA', 'SHAPE.LEN': 'SHAPE.LEN', });
lyr_SubndicedeConvivenciayCulturadePazporBarrio_1.set('fieldImages', {'FID': 'TextEdit', 'SCACODIGO': 'TextEdit', 'SCATIPO': 'TextEdit', 'SCANOMBRE': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Densidad_Eventos': 'TextEdit', 'Densidad_Intervenciones': 'TextEdit', 'ICC_2021': 'TextEdit', 'ICC_2023': 'TextEdit', 'Equip': 'TextEdit', 'I_194_Mul': 'TextEdit', 'I_127_Poi': 'TextEdit', 'Densidad_Eventos_2021': 'TextEdit', 'Densidad_Intervenciones_2021': 'TextEdit', 'Densidad_Eventos_2023': 'TextEdit', 'Densidad_Intervenciones_2023': 'TextEdit', 'Densidad_Eventos_2021_inv': 'TextEdit', 'Densidad_Eventos_2023_inv': 'TextEdit', 'Densidad_Intervenciones_2021_inv': 'TextEdit', 'Densidad_Intervenciones_2023_inv': 'TextEdit', 'Densidad_Intervenciones_inv': 'TextEdit', 'Densidad_Eventos_inv': 'TextEdit', 'Equip_inv': 'TextEdit', 'I_127_Poi_inv': 'TextEdit', 'delta_ICC': 'TextEdit', 'delta_eventos': 'TextEdit', 'delta_intervenciones': 'TextEdit', 'indice_intervencion': 'TextEdit', 'OBJECTID': 'Range', 'SUECODIGO': 'TextEdit', 'SUECSUELO': 'TextEdit', 'SUEAADMIN': 'TextEdit', 'SUEAREA': 'TextEdit', 'SHAPE.AREA': 'TextEdit', 'SHAPE.LEN': 'TextEdit', });
lyr_SubndicedeCulturaAmbientalporBarrio_2.set('fieldImages', {'FID': 'TextEdit', 'SCACODIGO': 'TextEdit', 'SCATIPO': 'TextEdit', 'SCANOMBRE': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Densidad_Eventos': 'TextEdit', 'Densidad_Intervenciones': 'TextEdit', 'ICC_2021': 'TextEdit', 'ICC_2023': 'TextEdit', 'Equip_x': 'TextEdit', 'IActores': 'TextEdit', 'IReserva': 'TextEdit', 'I_5_Poi': 'TextEdit', 'I_9_Poi': 'TextEdit', 'I_23_Poi': 'TextEdit', 'I_167_Pol': 'TextEdit', 'I_20_Mul': 'TextEdit', 'I_25_Poi': 'TextEdit', 'I_22_Mul': 'TextEdit', 'I_14_Mul': 'TextEdit', 'I_15_Mul': 'TextEdit', 'I_16_Poi': 'TextEdit', 'I_17_Mul': 'TextEdit', 'I_34_Poi': 'TextEdit', 'I_33_Mul': 'TextEdit', 'I_166_Poi': 'TextEdit', 'I_24_Poi': 'TextEdit', 'Densidad_Eventos_2021': 'TextEdit', 'Densidad_Intervenciones_2021': 'TextEdit', 'Densidad_Eventos_2023': 'TextEdit', 'Densidad_Intervenciones_2023': 'TextEdit', 'Densidad_Eventos_2021_inv': 'TextEdit', 'Densidad_Eventos_2023_inv': 'TextEdit', 'Equip_x_inv': 'TextEdit', 'I_9_Poi_inv': 'TextEdit', 'I_23_Poi_inv': 'TextEdit', 'I_16_Poi_inv': 'TextEdit', 'I_25_Poi_inv': 'TextEdit', 'I_166_Poi_inv': 'TextEdit', 'delta_ICC': 'TextEdit', 'delta_eventos': 'TextEdit', 'delta_intervenciones': 'TextEdit', 'indice_intervencion': 'TextEdit', 'OBJECTID': 'Range', 'SUECODIGO': 'TextEdit', 'SUECSUELO': 'TextEdit', 'SUEAADMIN': 'TextEdit', 'SUEAREA': 'TextEdit', 'SHAPE.AREA': 'TextEdit', 'SHAPE.LEN': 'TextEdit', });
lyr_SubndicedeCulturaPolticayCiudadanaporBarrio_3.set('fieldImages', {'FID': 'TextEdit', 'SCACODIGO': 'TextEdit', 'SCATIPO': 'TextEdit', 'SCANOMBRE': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Densidad_Eventos': 'TextEdit', 'Densidad_Intervenciones': 'TextEdit', 'ICC_2021': 'TextEdit', 'ICC_2023': 'TextEdit', 'IPolEquip': 'TextEdit', 'IPolActores': 'TextEdit', 'I_39_Mul': 'TextEdit', 'I_40_Mul': 'TextEdit', 'I_158_Pol': 'TextEdit', 'I_74_Poi': 'TextEdit', 'Densidad_Eventos_2021': 'TextEdit', 'Densidad_Intervenciones_2021': 'TextEdit', 'Densidad_Eventos_2023': 'TextEdit', 'Densidad_Intervenciones_2023': 'TextEdit', 'Densidad_Eventos_2021_inv': 'TextEdit', 'Densidad_Eventos_2023_inv': 'TextEdit', 'Densidad_Intervenciones_2021_inv': 'TextEdit', 'Densidad_Intervenciones_2023_inv': 'TextEdit', 'Densidad_Intervenciones_inv': 'TextEdit', 'Densidad_Eventos_inv': 'TextEdit', 'IPolEquip_inv': 'TextEdit', 'IPolActores_inv': 'TextEdit', 'I_158_Pol_inv': 'TextEdit', 'delta_ICC': 'TextEdit', 'delta_eventos': 'TextEdit', 'delta_intervenciones': 'TextEdit', 'indice_intervencion': 'TextEdit', 'OBJECTID': 'Range', 'SUECODIGO': 'TextEdit', 'SUECSUELO': 'TextEdit', 'SUEAADMIN': 'TextEdit', 'SUEAREA': 'TextEdit', 'SHAPE.AREA': 'TextEdit', 'SHAPE.LEN': 'TextEdit', });
lyr_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4.set('fieldImages', {'FID': 'TextEdit', 'SCACODIGO': 'TextEdit', 'SCATIPO': 'TextEdit', 'SCANOMBRE': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Densidad_Eventos': 'TextEdit', 'Densidad_Intervenciones': 'TextEdit', 'ICC_2021': 'TextEdit', 'ICC_2023': 'TextEdit', 'Equip': 'TextEdit', 'I_181_Mul': 'TextEdit', 'I_140_Pol': 'TextEdit', 'Densidad_Eventos_2021': 'TextEdit', 'Densidad_Intervenciones_2021': 'TextEdit', 'Densidad_Eventos_2023': 'TextEdit', 'Densidad_Intervenciones_2023': 'TextEdit', 'Equip_inv': 'TextEdit', 'I_181_Mul_inv': 'TextEdit', 'Densidad_Eventos_2021_inv': 'TextEdit', 'Densidad_Eventos_2023_inv': 'TextEdit', 'Densidad_Intervenciones_2021_inv': 'TextEdit', 'Densidad_Intervenciones_2023_inv': 'TextEdit', 'delta_ICC': 'TextEdit', 'delta_eventos': 'TextEdit', 'delta_intervenciones': 'TextEdit', 'indice_intervencion': 'TextEdit', 'OBJECTID': 'Range', 'SUECODIGO': 'TextEdit', 'SUECSUELO': 'TextEdit', 'SUEAADMIN': 'TextEdit', 'SUEAREA': 'TextEdit', 'SHAPE.AREA': 'TextEdit', 'SHAPE.LEN': 'TextEdit', });
lyr_SubndicedeEspacioPblicoporBarrio_5.set('fieldImages', {'FID': 'TextEdit', 'SCACODIGO': 'TextEdit', 'SCATIPO': 'TextEdit', 'SCANOMBRE': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Densidad_Eventos': 'TextEdit', 'Densidad_Intervenciones': 'TextEdit', 'ICC_2021': 'TextEdit', 'ICC_2023': 'TextEdit', 'Equip': 'TextEdit', 'I_71_Mul': 'TextEdit', 'I_55_Pol': 'TextEdit', 'I_39_Mul': 'TextEdit', 'I_145_Pol': 'TextEdit', 'I_40_Mul': 'TextEdit', 'I_140_Pol': 'TextEdit', 'I_196_Pol': 'TextEdit', 'I_3_Mul': 'TextEdit', 'I_149_Pol': 'TextEdit', 'Densidad_Eventos_2021': 'TextEdit', 'Densidad_Intervenciones_2021': 'TextEdit', 'Densidad_Eventos_2023': 'TextEdit', 'Densidad_Intervenciones_2023': 'TextEdit', 'Equip_inv': 'TextEdit', 'I_71_Mul_inv': 'TextEdit', 'I_55_Pol_inv': 'TextEdit', 'I_145_Pol_inv': 'TextEdit', 'I_140_Pol_inv': 'TextEdit', 'I_196_Pol_inv': 'TextEdit', 'I_3_Mul_inv': 'TextEdit', 'Densidad_Eventos_inv': 'TextEdit', 'delta_ICC': 'TextEdit', 'delta_eventos': 'TextEdit', 'delta_intervenciones': 'TextEdit', 'indice_intervencion': 'TextEdit', 'OBJECTID': 'Range', 'SUECODIGO': 'TextEdit', 'SUECSUELO': 'TextEdit', 'SUEAADMIN': 'TextEdit', 'SUEAREA': 'TextEdit', 'SHAPE.AREA': 'TextEdit', 'SHAPE.LEN': 'TextEdit', });
lyr_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6.set('fieldImages', {'FID': 'TextEdit', 'SCACODIGO': 'TextEdit', 'SCATIPO': 'TextEdit', 'SCANOMBRE': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Densidad_Eventos': 'TextEdit', 'Densidad_Intervenciones': 'TextEdit', 'ICC_2021': 'TextEdit', 'ICC_2023': 'TextEdit', 'Equip': 'TextEdit', 'I_125_Poi': 'TextEdit', 'I_101_Poi': 'TextEdit', 'I_78_Poi': 'TextEdit', 'I_126_Poi': 'TextEdit', 'I_129_Poi': 'TextEdit', 'I_111_Poi': 'TextEdit', 'I_199_Pol': 'TextEdit', 'I_106_Poi': 'TextEdit', 'I_142_Pol': 'TextEdit', 'I_102_Poi': 'TextEdit', 'I_122_Poi': 'TextEdit', 'I_123_Poi': 'TextEdit', 'I_108_Poi': 'TextEdit', 'I_104_Poi': 'TextEdit', 'I_132_Poi': 'TextEdit', 'I_98_Poi': 'TextEdit', 'I_120_Poi': 'TextEdit', 'I_99_Poi': 'TextEdit', 'Densidad_Eventos_2021': 'TextEdit', 'Densidad_Intervenciones_2021': 'TextEdit', 'Densidad_Eventos_2023': 'TextEdit', 'Densidad_Intervenciones_2023': 'TextEdit', 'Equip_inv': 'TextEdit', 'I_125_Poi_inv': 'TextEdit', 'I_101_Poi_inv': 'TextEdit', 'I_78_Poi_inv': 'TextEdit', 'I_126_Poi_inv': 'TextEdit', 'I_129_Poi_inv': 'TextEdit', 'I_111_Poi_inv': 'TextEdit', 'I_106_Poi_inv': 'TextEdit', 'I_102_Poi_inv': 'TextEdit', 'I_122_Poi_inv': 'TextEdit', 'I_123_Poi_inv': 'TextEdit', 'I_108_Poi_inv': 'TextEdit', 'I_104_Poi_inv': 'TextEdit', 'I_132_Poi_inv': 'TextEdit', 'I_98_Poi_inv': 'TextEdit', 'I_120_Poi_inv': 'TextEdit', 'I_99_Poi_inv': 'TextEdit', 'Densidad_Eventos_2021_inv': 'TextEdit', 'Densidad_Eventos_2023_inv': 'TextEdit', 'Densidad_Intervenciones_2021_inv': 'TextEdit', 'Densidad_Intervenciones_2023_inv': 'TextEdit', 'delta_ICC': 'TextEdit', 'delta_eventos': 'TextEdit', 'delta_intervenciones': 'TextEdit', 'indice_intervencion': 'TextEdit', 'OBJECTID': 'Range', 'SUECODIGO': 'TextEdit', 'SUECSUELO': 'TextEdit', 'SUEAADMIN': 'TextEdit', 'SUEAREA': 'TextEdit', 'SHAPE.AREA': 'TextEdit', 'SHAPE.LEN': 'TextEdit', });
lyr_SubndicedeMovilidadporBarrio_7.set('fieldImages', {'FID': 'TextEdit', 'SCACODIGO': 'TextEdit', 'SCATIPO': 'TextEdit', 'SCANOMBRE': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Densidad_Eventos': 'TextEdit', 'Densidad_Intervenciones': 'TextEdit', 'ICC_2021': 'TextEdit', 'ICC_2023': 'TextEdit', 'Equip': 'TextEdit', 'I_71_Mul': 'TextEdit', 'I_42_Mul': 'TextEdit', 'I_153_Poi': 'TextEdit', 'I_139_Lin': 'TextEdit', 'I_159_Lin': 'TextEdit', 'Densidad_Eventos_2021': 'TextEdit', 'Densidad_Intervenciones_2021': 'TextEdit', 'Densidad_Eventos_2023': 'TextEdit', 'Densidad_Intervenciones_2023': 'TextEdit', 'Equip_inv': 'TextEdit', 'I_71_Mul_inv': 'TextEdit', 'I_153_Poi_inv': 'TextEdit', 'I_139_Lin_inv': 'TextEdit', 'I_159_Lin_inv': 'TextEdit', 'Densidad_Eventos_2021_inv': 'TextEdit', 'Densidad_Eventos_2023_inv': 'TextEdit', 'Densidad_Intervenciones_2021_inv': 'TextEdit', 'Densidad_Intervenciones_2023_inv': 'TextEdit', 'delta_ICC': 'TextEdit', 'delta_eventos': 'TextEdit', 'delta_intervenciones': 'TextEdit', 'indice_intervencion': 'TextEdit', 'OBJECTID': 'Range', 'SUECODIGO': 'TextEdit', 'SUECSUELO': 'TextEdit', 'SUEAADMIN': 'TextEdit', 'SUEAREA': 'TextEdit', 'SHAPE.AREA': 'TextEdit', 'SHAPE.LEN': 'TextEdit', });
lyr_SubndicedeConvivenciayCulturadePazporBarrio_1.set('fieldLabels', {'FID': 'hidden field', 'SCACODIGO': 'hidden field', 'SCATIPO': 'hidden field', 'SCANOMBRE': 'inline label - visible with data', 'SHAPE_AREA': 'hidden field', 'SHAPE_LEN': 'hidden field', 'Densidad_Eventos': 'hidden field', 'Densidad_Intervenciones': 'hidden field', 'ICC_2021': 'hidden field', 'ICC_2023': 'hidden field', 'Equip': 'hidden field', 'I_194_Mul': 'hidden field', 'I_127_Poi': 'hidden field', 'Densidad_Eventos_2021': 'hidden field', 'Densidad_Intervenciones_2021': 'hidden field', 'Densidad_Eventos_2023': 'hidden field', 'Densidad_Intervenciones_2023': 'hidden field', 'Densidad_Eventos_2021_inv': 'hidden field', 'Densidad_Eventos_2023_inv': 'hidden field', 'Densidad_Intervenciones_2021_inv': 'hidden field', 'Densidad_Intervenciones_2023_inv': 'hidden field', 'Densidad_Intervenciones_inv': 'hidden field', 'Densidad_Eventos_inv': 'hidden field', 'Equip_inv': 'hidden field', 'I_127_Poi_inv': 'hidden field', 'delta_ICC': 'hidden field', 'delta_eventos': 'hidden field', 'delta_intervenciones': 'hidden field', 'indice_intervencion': 'inline label - visible with data', 'OBJECTID': 'hidden field', 'SUECODIGO': 'hidden field', 'SUECSUELO': 'hidden field', 'SUEAADMIN': 'hidden field', 'SUEAREA': 'hidden field', 'SHAPE.AREA': 'hidden field', 'SHAPE.LEN': 'hidden field', });
lyr_SubndicedeCulturaAmbientalporBarrio_2.set('fieldLabels', {'FID': 'hidden field', 'SCACODIGO': 'hidden field', 'SCATIPO': 'hidden field', 'SCANOMBRE': 'inline label - visible with data', 'SHAPE_AREA': 'hidden field', 'SHAPE_LEN': 'hidden field', 'Densidad_Eventos': 'hidden field', 'Densidad_Intervenciones': 'hidden field', 'ICC_2021': 'hidden field', 'ICC_2023': 'hidden field', 'Equip_x': 'hidden field', 'IActores': 'hidden field', 'IReserva': 'hidden field', 'I_5_Poi': 'hidden field', 'I_9_Poi': 'hidden field', 'I_23_Poi': 'hidden field', 'I_167_Pol': 'hidden field', 'I_20_Mul': 'hidden field', 'I_25_Poi': 'hidden field', 'I_22_Mul': 'hidden field', 'I_14_Mul': 'hidden field', 'I_15_Mul': 'hidden field', 'I_16_Poi': 'hidden field', 'I_17_Mul': 'hidden field', 'I_34_Poi': 'hidden field', 'I_33_Mul': 'hidden field', 'I_166_Poi': 'hidden field', 'I_24_Poi': 'hidden field', 'Densidad_Eventos_2021': 'hidden field', 'Densidad_Intervenciones_2021': 'hidden field', 'Densidad_Eventos_2023': 'hidden field', 'Densidad_Intervenciones_2023': 'hidden field', 'Densidad_Eventos_2021_inv': 'hidden field', 'Densidad_Eventos_2023_inv': 'hidden field', 'Equip_x_inv': 'hidden field', 'I_9_Poi_inv': 'hidden field', 'I_23_Poi_inv': 'hidden field', 'I_16_Poi_inv': 'hidden field', 'I_25_Poi_inv': 'hidden field', 'I_166_Poi_inv': 'hidden field', 'delta_ICC': 'hidden field', 'delta_eventos': 'hidden field', 'delta_intervenciones': 'hidden field', 'indice_intervencion': 'inline label - visible with data', 'OBJECTID': 'hidden field', 'SUECODIGO': 'hidden field', 'SUECSUELO': 'hidden field', 'SUEAADMIN': 'hidden field', 'SUEAREA': 'hidden field', 'SHAPE.AREA': 'hidden field', 'SHAPE.LEN': 'hidden field', });
lyr_SubndicedeCulturaPolticayCiudadanaporBarrio_3.set('fieldLabels', {'FID': 'hidden field', 'SCACODIGO': 'hidden field', 'SCATIPO': 'hidden field', 'SCANOMBRE': 'inline label - visible with data', 'SHAPE_AREA': 'hidden field', 'SHAPE_LEN': 'hidden field', 'Densidad_Eventos': 'hidden field', 'Densidad_Intervenciones': 'hidden field', 'ICC_2021': 'hidden field', 'ICC_2023': 'hidden field', 'IPolEquip': 'hidden field', 'IPolActores': 'hidden field', 'I_39_Mul': 'hidden field', 'I_40_Mul': 'hidden field', 'I_158_Pol': 'hidden field', 'I_74_Poi': 'hidden field', 'Densidad_Eventos_2021': 'hidden field', 'Densidad_Intervenciones_2021': 'hidden field', 'Densidad_Eventos_2023': 'hidden field', 'Densidad_Intervenciones_2023': 'hidden field', 'Densidad_Eventos_2021_inv': 'hidden field', 'Densidad_Eventos_2023_inv': 'hidden field', 'Densidad_Intervenciones_2021_inv': 'hidden field', 'Densidad_Intervenciones_2023_inv': 'hidden field', 'Densidad_Intervenciones_inv': 'hidden field', 'Densidad_Eventos_inv': 'hidden field', 'IPolEquip_inv': 'hidden field', 'IPolActores_inv': 'hidden field', 'I_158_Pol_inv': 'hidden field', 'delta_ICC': 'hidden field', 'delta_eventos': 'hidden field', 'delta_intervenciones': 'hidden field', 'indice_intervencion': 'inline label - visible with data', 'OBJECTID': 'hidden field', 'SUECODIGO': 'hidden field', 'SUECSUELO': 'hidden field', 'SUEAADMIN': 'hidden field', 'SUEAREA': 'hidden field', 'SHAPE.AREA': 'hidden field', 'SHAPE.LEN': 'hidden field', });
lyr_SubndicedeEquidaddeGneroyEliminacindelMachismoporBarrio_4.set('fieldLabels', {'FID': 'hidden field', 'SCACODIGO': 'hidden field', 'SCATIPO': 'hidden field', 'SCANOMBRE': 'inline label - visible with data', 'SHAPE_AREA': 'hidden field', 'SHAPE_LEN': 'hidden field', 'Densidad_Eventos': 'hidden field', 'Densidad_Intervenciones': 'hidden field', 'ICC_2021': 'hidden field', 'ICC_2023': 'hidden field', 'Equip': 'hidden field', 'I_181_Mul': 'hidden field', 'I_140_Pol': 'hidden field', 'Densidad_Eventos_2021': 'hidden field', 'Densidad_Intervenciones_2021': 'hidden field', 'Densidad_Eventos_2023': 'hidden field', 'Densidad_Intervenciones_2023': 'hidden field', 'Equip_inv': 'hidden field', 'I_181_Mul_inv': 'hidden field', 'Densidad_Eventos_2021_inv': 'hidden field', 'Densidad_Eventos_2023_inv': 'hidden field', 'Densidad_Intervenciones_2021_inv': 'hidden field', 'Densidad_Intervenciones_2023_inv': 'hidden field', 'delta_ICC': 'hidden field', 'delta_eventos': 'hidden field', 'delta_intervenciones': 'hidden field', 'indice_intervencion': 'hidden field', 'OBJECTID': 'hidden field', 'SUECODIGO': 'hidden field', 'SUECSUELO': 'hidden field', 'SUEAADMIN': 'hidden field', 'SUEAREA': 'hidden field', 'SHAPE.AREA': 'hidden field', 'SHAPE.LEN': 'hidden field', });
lyr_SubndicedeEspacioPblicoporBarrio_5.set('fieldLabels', {'FID': 'hidden field', 'SCACODIGO': 'hidden field', 'SCATIPO': 'hidden field', 'SCANOMBRE': 'inline label - visible with data', 'SHAPE_AREA': 'hidden field', 'SHAPE_LEN': 'hidden field', 'Densidad_Eventos': 'hidden field', 'Densidad_Intervenciones': 'hidden field', 'ICC_2021': 'hidden field', 'ICC_2023': 'hidden field', 'Equip': 'hidden field', 'I_71_Mul': 'hidden field', 'I_55_Pol': 'hidden field', 'I_39_Mul': 'hidden field', 'I_145_Pol': 'hidden field', 'I_40_Mul': 'hidden field', 'I_140_Pol': 'hidden field', 'I_196_Pol': 'hidden field', 'I_3_Mul': 'hidden field', 'I_149_Pol': 'hidden field', 'Densidad_Eventos_2021': 'hidden field', 'Densidad_Intervenciones_2021': 'hidden field', 'Densidad_Eventos_2023': 'hidden field', 'Densidad_Intervenciones_2023': 'hidden field', 'Equip_inv': 'hidden field', 'I_71_Mul_inv': 'hidden field', 'I_55_Pol_inv': 'hidden field', 'I_145_Pol_inv': 'hidden field', 'I_140_Pol_inv': 'hidden field', 'I_196_Pol_inv': 'hidden field', 'I_3_Mul_inv': 'hidden field', 'Densidad_Eventos_inv': 'hidden field', 'delta_ICC': 'hidden field', 'delta_eventos': 'hidden field', 'delta_intervenciones': 'hidden field', 'indice_intervencion': 'inline label - visible with data', 'OBJECTID': 'hidden field', 'SUECODIGO': 'hidden field', 'SUECSUELO': 'hidden field', 'SUEAADMIN': 'hidden field', 'SUEAREA': 'hidden field', 'SHAPE.AREA': 'hidden field', 'SHAPE.LEN': 'hidden field', });
lyr_SubndicedeInclusineIdentidadesSocialesDiversasporBarrio_6.set('fieldLabels', {'FID': 'hidden field', 'SCACODIGO': 'hidden field', 'SCATIPO': 'hidden field', 'SCANOMBRE': 'inline label - visible with data', 'SHAPE_AREA': 'hidden field', 'SHAPE_LEN': 'hidden field', 'Densidad_Eventos': 'hidden field', 'Densidad_Intervenciones': 'hidden field', 'ICC_2021': 'hidden field', 'ICC_2023': 'hidden field', 'Equip': 'hidden field', 'I_125_Poi': 'hidden field', 'I_101_Poi': 'hidden field', 'I_78_Poi': 'hidden field', 'I_126_Poi': 'hidden field', 'I_129_Poi': 'hidden field', 'I_111_Poi': 'hidden field', 'I_199_Pol': 'hidden field', 'I_106_Poi': 'hidden field', 'I_142_Pol': 'hidden field', 'I_102_Poi': 'hidden field', 'I_122_Poi': 'hidden field', 'I_123_Poi': 'hidden field', 'I_108_Poi': 'hidden field', 'I_104_Poi': 'hidden field', 'I_132_Poi': 'hidden field', 'I_98_Poi': 'hidden field', 'I_120_Poi': 'hidden field', 'I_99_Poi': 'hidden field', 'Densidad_Eventos_2021': 'hidden field', 'Densidad_Intervenciones_2021': 'hidden field', 'Densidad_Eventos_2023': 'hidden field', 'Densidad_Intervenciones_2023': 'hidden field', 'Equip_inv': 'hidden field', 'I_125_Poi_inv': 'hidden field', 'I_101_Poi_inv': 'hidden field', 'I_78_Poi_inv': 'hidden field', 'I_126_Poi_inv': 'hidden field', 'I_129_Poi_inv': 'hidden field', 'I_111_Poi_inv': 'hidden field', 'I_106_Poi_inv': 'hidden field', 'I_102_Poi_inv': 'hidden field', 'I_122_Poi_inv': 'hidden field', 'I_123_Poi_inv': 'hidden field', 'I_108_Poi_inv': 'hidden field', 'I_104_Poi_inv': 'hidden field', 'I_132_Poi_inv': 'hidden field', 'I_98_Poi_inv': 'hidden field', 'I_120_Poi_inv': 'hidden field', 'I_99_Poi_inv': 'hidden field', 'Densidad_Eventos_2021_inv': 'hidden field', 'Densidad_Eventos_2023_inv': 'hidden field', 'Densidad_Intervenciones_2021_inv': 'hidden field', 'Densidad_Intervenciones_2023_inv': 'hidden field', 'delta_ICC': 'hidden field', 'delta_eventos': 'hidden field', 'delta_intervenciones': 'hidden field', 'indice_intervencion': 'inline label - visible with data', 'OBJECTID': 'hidden field', 'SUECODIGO': 'hidden field', 'SUECSUELO': 'hidden field', 'SUEAADMIN': 'hidden field', 'SUEAREA': 'hidden field', 'SHAPE.AREA': 'hidden field', 'SHAPE.LEN': 'hidden field', });
lyr_SubndicedeMovilidadporBarrio_7.set('fieldLabels', {'FID': 'hidden field', 'SCACODIGO': 'hidden field', 'SCATIPO': 'hidden field', 'SCANOMBRE': 'inline label - visible with data', 'SHAPE_AREA': 'hidden field', 'SHAPE_LEN': 'hidden field', 'Densidad_Eventos': 'hidden field', 'Densidad_Intervenciones': 'hidden field', 'ICC_2021': 'hidden field', 'ICC_2023': 'hidden field', 'Equip': 'hidden field', 'I_71_Mul': 'hidden field', 'I_42_Mul': 'hidden field', 'I_153_Poi': 'hidden field', 'I_139_Lin': 'hidden field', 'I_159_Lin': 'hidden field', 'Densidad_Eventos_2021': 'hidden field', 'Densidad_Intervenciones_2021': 'hidden field', 'Densidad_Eventos_2023': 'hidden field', 'Densidad_Intervenciones_2023': 'hidden field', 'Equip_inv': 'hidden field', 'I_71_Mul_inv': 'hidden field', 'I_153_Poi_inv': 'hidden field', 'I_139_Lin_inv': 'hidden field', 'I_159_Lin_inv': 'hidden field', 'Densidad_Eventos_2021_inv': 'hidden field', 'Densidad_Eventos_2023_inv': 'hidden field', 'Densidad_Intervenciones_2021_inv': 'hidden field', 'Densidad_Intervenciones_2023_inv': 'hidden field', 'delta_ICC': 'hidden field', 'delta_eventos': 'hidden field', 'delta_intervenciones': 'hidden field', 'indice_intervencion': 'inline label - visible with data', 'OBJECTID': 'hidden field', 'SUECODIGO': 'hidden field', 'SUECSUELO': 'hidden field', 'SUEAADMIN': 'hidden field', 'SUEAREA': 'hidden field', 'SHAPE.AREA': 'hidden field', 'SHAPE.LEN': 'hidden field', });
lyr_SubndicedeMovilidadporBarrio_7.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});